splash = false

wallpaper {
    monitor = DP-2
    path = /home/shizu/Pictures/Wallpapers/Blackpink.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/shizu/Pictures/Wallpapers/Blackpink.jpg
    fit_mode = cover
}
