hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpm enable hyprglass")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("steam")
    hl.exec_cmd("vesktop")
    hl.exec_cmd("zen-browser")
end)